# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b57cf0c5909378caf349d9c85a93d88be18237b10108409e73633f0707d480b589519d50b8084c6873cc2c62fbe2281271fbdbd32a620c48ff17017200f2337

test:
  secret_key_base: 00c41bac645d86399fb659169314226bbd1069ecd395a9688b823f24c857cdd22b60c729cb3fdae6e0789f1a69e72a90a3a803323aba41598bc5c4f3e9abb9bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
